### ISSUE TITLE
Is file input supported?

### ISSUE THREAD

**Issue by youanden** [jspears/subschema#19]
Or should I create a custom input for this?

**Comment by jspears** [comment]
Due to the server/client side complexity of file upload, I punted on it.  I suppose I could do a super simple one, but rarely are those used anymore.   So afraid you are on your own.   If you submitted a PR, I would be happy to add it back.    It shouldn't be hard to add you own component.  

You could also use a Text in put with dataType='file' you would aslo pass the form enctype="multipart/form-data" to the <form tag. 

I'll see if this actually works.
